<?php
define('DOMAINTYPE','off');
define('CH','exam_');
define('CDO','');
define('CP','/');
define('CRT',180);
define('CS','xn9dylsl012002');
define('HE','utf-8');
define('PN',10);
define('TIME',time());
if(dirname($_SERVER['SCRIPT_NAME']))
define('WP','http://'.$_SERVER['SERVER_NAME'].dirname($_SERVER['SCRIPT_NAME']));
else
define('WP','http://'.$_SERVER['SERVER_NAME'].'/');

define('DB','51elab_ems');
define('DH','localhost');
define('DU','root');
define('DP','root');
define('DTH','x2_');
//sso 
define('SSOURL','http://sso.51elab.com/sso/checktoken.51elab?c=sdfsdfw34');
define('SSOLOGOUTURL','http://sso.51elab.com/sso/logout.51elab?c=http://edu.51elab.com/ems');
//sso 
define('SSOKEY','qweqweqweqwe');
//
define('BALANCE','http://sso.51elab.com/api/balance.51elab?c=sdfsdfw34');
//
define('PAYTO','http://sso.51elab.com/api/paycurl.51elab?id=sdfsdfw34');
?>