/*
 highcharts js v4.0.1 (2014-04-24)
 exporting module

 (c) 2010-2014 torstein honsi

 license: www.highcharts.com/license
*/
(function(f){var a=f.chart,t=f.addevent,b=f.removeevent,l=f.createelement,o=f.discardelement,v=f.css,k=f.merge,r=f.each,p=f.extend,d=math.max,j=document,c=window,e=f.istouchdevice,f=f.renderer.prototype.symbols,s=f.getoptions(),y;p(s.lang,{printchart:"print chart",downloadpng:"download png image",downloadjpeg:"download jpeg image",downloadpdf:"download pdf document",downloadsvg:"download svg vector image",contextbuttontitle:"chart context menu"});s.navigation={menustyle:{border:"1px solid #a0a0a0",
background:"#ffffff",padding:"5px 0"},menuitemstyle:{padding:"0 10px",background:"none",color:"#303030",fontsize:e?"14px":"11px"},menuitemhoverstyle:{background:"#4572a5",color:"#ffffff"},buttonoptions:{symbolfill:"#e0e0e0",symbolsize:14,symbolstroke:"#666",symbolstrokewidth:3,symbolx:12.5,symboly:10.5,align:"right",buttonspacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalalign:"top",width:24}};s.exporting={type:"image/png",url:"http://export.highcharts.com/",buttons:{contextbutton:{menuclassname:"highcharts-contextmenu",
symbol:"menu",_titlekey:"contextbuttontitle",menuitems:[{textkey:"printchart",onclick:function(){this.print()}},{separator:!0},{textkey:"downloadpng",onclick:function(){this.exportchart()}},{textkey:"downloadjpeg",onclick:function(){this.exportchart({type:"image/jpeg"})}},{textkey:"downloadpdf",onclick:function(){this.exportchart({type:"application/pdf"})}},{textkey:"downloadsvg",onclick:function(){this.exportchart({type:"image/svg+xml"})}}]}}};f.post=function(b,a,d){var c,b=l("form",k({method:"post",
action:b,enctype:"multipart/form-data"},d),{display:"none"},j.body);for(c in a)l("input",{type:"hidden",name:c,value:a[c]},null,b);b.submit();o(b)};p(a.prototype,{getsvg:function(b){var a=this,d,c,z,h,g=k(a.options,b);if(!j.createelementns)j.createelementns=function(a,b){return j.createelement(b)};b=l("div",null,{position:"absolute",top:"-9999em",width:a.chartwidth+"px",height:a.chartheight+"px"},j.body);c=a.renderto.style.width;h=a.renderto.style.height;c=g.exporting.sourcewidth||g.chart.width||
/px$/.test(c)&&parseint(c,10)||600;h=g.exporting.sourceheight||g.chart.height||/px$/.test(h)&&parseint(h,10)||400;p(g.chart,{animation:!1,renderto:b,forexport:!0,width:c,height:h});g.exporting.enabled=!1;g.series=[];r(a.series,function(a){z=k(a.options,{animation:!1,showcheckbox:!1,visible:a.visible});z.isinternal||g.series.push(z)});d=new f.chart(g,a.callback);r(["xaxis","yaxis"],function(b){r(a[b],function(a,c){var g=d[b][c],f=a.getextremes(),h=f.usermin,f=f.usermax;g&&(h!==void 0||f!==void 0)&&
g.setextremes(h,f,!0,!1)})});c=d.container.innerhtml;g=null;d.destroy();o(b);c=c.replace(/zindex="[^"]+"/g,"").replace(/isshadow="[^"]+"/g,"").replace(/symbolname="[^"]+"/g,"").replace(/jquery[0-9]+="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ href=/g," xlink:href=").replace(/\n/," ").replace(/<\/svg>.*?$/,"</svg>").replace(/&nbsp;/g," ").replace(/&shy;/g,"­").replace(/<img /g,"<image ").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,
'width="$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href="$1"/>').replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" >]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(a){return a.tolowercase()});return c=c.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'")},exportchart:function(b,a){var b=b||{},d=this.options.exporting,d=this.getsvg(k({chart:{borderradius:0}},d.chartoptions,a,{exporting:{sourcewidth:b.sourcewidth||
d.sourcewidth,sourceheight:b.sourceheight||d.sourceheight}})),b=k(this.options.exporting,b);f.post(b.url,{filename:b.filename||"chart",type:b.type,width:b.width||0,scale:b.scale||2,svg:d},b.formattributes)},print:function(){var b=this,a=b.container,d=[],c=a.parentnode,f=j.body,h=f.childnodes;if(!b.isprinting)b.isprinting=!0,r(h,function(a,b){if(a.nodetype===1)d[b]=a.style.display,a.style.display="none"}),f.appendchild(a),c.focus(),c.print(),settimeout(function(){c.appendchild(a);r(h,function(a,b){if(a.nodetype===
1)a.style.display=d[b]});b.isprinting=!1},1e3)},contextmenu:function(b,a,d,c,f,h,g){var e=this,k=e.options.navigation,q=k.menuitemstyle,m=e.chartwidth,n=e.chartheight,j="cache-"+b,i=e[j],u=d(f,h),w,x,o,s=function(a){e.pointer.inclass(a.target,b)||x()};if(!i)e[j]=i=l("div",{classname:b},{position:"absolute",zindex:1e3,padding:u+"px"},e.container),w=l("div",null,p({mozboxshadow:"3px 3px 10px #888",webkitboxshadow:"3px 3px 10px #888",boxshadow:"3px 3px 10px #888"},k.menustyle),i),x=function(){v(i,{display:"none"});
g&&g.setstate(0);e.openmenu=!1},t(i,"mouseleave",function(){o=settimeout(x,500)}),t(i,"mouseenter",function(){cleartimeout(o)}),t(document,"mouseup",s),t(e,"destroy",function(){b(document,"mouseup",s)}),r(a,function(a){if(a){var b=a.separator?l("hr",null,null,w):l("div",{onmouseover:function(){v(this,k.menuitemhoverstyle)},onmouseout:function(){v(this,q)},onclick:function(){x();a.onclick.apply(e,arguments)},innerhtml:a.text||e.options.lang[a.textkey]},p({cursor:"pointer"},q),w);e.exportdivelements.push(b)}}),
e.exportdivelements.push(w,i),e.exportmenuwidth=i.offsetwidth,e.exportmenuheight=i.offsetheight;a={display:"block"};d+e.exportmenuwidth>m?a.right=m-d-f-u+"px":a.left=d-u+"px";c+h+e.exportmenuheight>n&&g.alignoptions.verticalalign!=="top"?a.bottom=n-c-u+"px":a.top=c+h-u+"px";v(i,a);e.openmenu=!0},addbutton:function(b){var a=this,d=a.renderer,c=k(a.options.navigation.buttonoptions,b),j=c.onclick,h=c.menuitems,g,e,l={stroke:c.symbolstroke,fill:c.symbolfill},q=c.symbolsize||12;if(!a.btncount)a.btncount=
0;if(!a.exportdivelements)a.exportdivelements=[],a.exportsvgelements=[];if(c.enabled!==!1){var m=c.theme,n=m.states,o=n&&n.hover,n=n&&n.select,i;delete m.states;j?i=function(){j.apply(a,arguments)}:h&&(i=function(){a.contextmenu(e.menuclassname,h,e.translatex,e.translatey,e.width,e.height,e);e.setstate(2)});c.text&&c.symbol?m.paddingleft=f.pick(m.paddingleft,25):c.text||p(m,{width:c.width,height:c.height,padding:0});e=d.button(c.text,0,0,i,m,o,n).attr({title:a.options.lang[c._titlekey],"stroke-linecap":"round"});
e.menuclassname=b.menuclassname||"highcharts-menu-"+a.btncount++;c.symbol&&(g=d.symbol(c.symbol,c.symbolx-q/2,c.symboly-q/2,q,q).attr(p(l,{"stroke-width":c.symbolstrokewidth||1,zindex:1})).add(e));e.add().align(p(c,{width:e.width,x:f.pick(c.x,y)}),!0,"spacingbox");y+=(e.width+c.buttonspacing)*(c.align==="right"?-1:1);a.exportsvgelements.push(e,g)}},destroyexport:function(b){var b=b.target,a,d;for(a=0;a<b.exportsvgelements.length;a++)if(d=b.exportsvgelements[a])d.onclick=d.ontouchstart=null,b.exportsvgelements[a]=
d.destroy();for(a=0;a<b.exportdivelements.length;a++)d=b.exportdivelements[a],b(d,"mouseleave"),b.exportdivelements[a]=d.onmouseout=d.onmouseover=d.ontouchstart=d.onclick=null,o(d)}});f.menu=function(b,a,d,c){return["m",b,a+2.5,"l",b+d,a+2.5,"m",b,a+c/2+0.5,"l",b+d,a+c/2+0.5,"m",b,a+c-1.5,"l",b+d,a+c-1.5]};a.prototype.callbacks.push(function(b){var a,d=b.options.exporting,c=d.buttons;y=0;if(d.enabled!==!1){for(a in c)b.addbutton(c[a]);t(b,"destroy",b.destroyexport)}})})(highcharts);
